<?php

namespace App\Services;

use App\Models\Customer;
use App\Models\CustomerLedger;
use App\Services\PartyLedgerService;
use App\Models\UserGroup;
use App\Models\Zone;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class CustomerImportService
{
    public const COLUMN_MAP = [
        'customer_type' => 'Customer Type',
        'customer_name' => 'Customer Name',
        'customer_name_ur' => 'Customer Name (Urdu)',
        'zone' => 'Zone',
        'cnic' => 'NTN / CNIC',
        'filer_type' => 'Filer Type',
        'contact_person' => 'Contact Person',
        'mobile' => 'Mobile',
        'email_address' => 'Email Address',
        'contact_person_2' => 'Contact Person 2',
        'mobile_2' => 'Mobile 2',
        'email_address_2' => 'Email Address 2',
        'opening_balance' => 'Opening Balance',
        'user_groups' => 'User Groups',
        'transport_ur' => 'Transporter (Urdu)',
        'address' => 'Address',
        'address_ur' => 'Address (Urdu)',
    ];

    public function buildTemplateSpreadsheet(): Spreadsheet
    {
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Customers');

        $headers = array_values(self::COLUMN_MAP);
        foreach ($headers as $colIndex => $header) {
            $column = Coordinate::stringFromColumnIndex($colIndex + 1);
            $sheet->setCellValue($column . '1', $header);
        }

        $zoneSample = Zone::query()->value('zone') ?? 'Zone A';
        $groupSample = UserGroup::query()->value('group_name') ?? 'Group 1';

        $sampleRows = [
            [
                'Main Customer',
                'ABC Traders',
                'اے بی سی ٹریڈرز',
                $zoneSample,
                '1234567890123',
                'filer',
                'Ali Ahmed',
                '03001234567',
                'abc@example.com',
                'Hassan Khan',
                '03007654321',
                'hassan@example.com',
                '5000',
                $groupSample,
                'ٹرانسپورٹر نام',
                '123 Main Street, Lahore',
                'لاہور، مین سٹریٹ',
            ],
            [
                'Walking Customer',
                'Walk-in Customer',
                'واک اِن کسٹمر',
                $zoneSample,
                '',
                'non filer',
                '',
                '03009998877',
                '',
                '',
                '',
                '',
                '0',
                '',
                '',
                'Counter Sale / Walk-in',
                'کاؤنٹر سیل',
            ],
        ];

        foreach ($sampleRows as $rowIndex => $sampleRow) {
            $excelRow = $rowIndex + 2;
            foreach ($sampleRow as $colIndex => $value) {
                $column = Coordinate::stringFromColumnIndex($colIndex + 1);
                $sheet->setCellValue($column . $excelRow, $value);
            }
        }

        $lastCol = count($headers);
        $lastColumnLetter = Coordinate::stringFromColumnIndex($lastCol);
        $sheet->getStyle('A1:' . $lastColumnLetter . '1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['rgb' => '7BBCBE'],
            ],
        ]);

        $sheet->getStyle('A2:' . $lastColumnLetter . '3')->applyFromArray([
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['rgb' => 'FFF9E6'],
            ],
            'font' => ['italic' => true, 'color' => ['rgb' => '666666']],
        ]);

        foreach (range(1, $lastCol) as $col) {
            $sheet->getColumnDimension(Coordinate::stringFromColumnIndex($col))->setAutoSize(true);
        }

        $instructions = $spreadsheet->createSheet();
        $instructions->setTitle('Instructions');
        $instructions->setCellValue('A1', 'Customer Import Instructions');
        $instructions->getStyle('A1')->getFont()->setBold(true)->setSize(14);

        $lines = [
            '',
            '1. Fill customer data in the "Customers" sheet starting from row 2.',
            '2. Do not change or remove the header row (row 1).',
            '3. Customer ID is auto-generated by the system on import.',
            '4. Customer Type: Main Customer OR Walking Customer',
            '5. Row 2 = Main Customer sample | Row 3 = Walking Customer sample (yellow rows).',
            '6. Main Customer: full details (CNIC, contacts, opening balance, etc.).',
            '7. Walking Customer: usually name + mobile is enough; other fields can stay blank.',
            '8. Filer Type: filer OR non filer OR exempt',
            '9. Opening Balance: numeric only (leave blank or 0 for no opening balance)',
            '10. User Groups: comma-separated group names (Admin only). Leave blank to skip.',
            '11. For non-admin users, your assigned groups are applied automatically.',
            '12. Delete sample rows (2 & 3) before importing your real data.',
            '13. Save file as .xlsx and upload from Customers > Import Excel.',
        ];
        foreach ($lines as $index => $line) {
            $instructions->setCellValue('A' . ($index + 2), $line);
        }
        $instructions->getColumnDimension('A')->setWidth(90);

        $reference = $spreadsheet->createSheet();
        $reference->setTitle('Reference');
        $reference->setCellValue('A1', 'Zones');
        $reference->setCellValue('B1', 'Filer Types');
        $reference->setCellValue('C1', 'User Groups');
        $reference->setCellValue('D1', 'Customer Types');
        $reference->getStyle('A1:D1')->getFont()->setBold(true);

        $zones = Zone::query()->pluck('zone')->filter()->values();
        $filerTypes = ['filer', 'non filer', 'exempt'];
        $groups = UserGroup::query()->pluck('group_name')->filter()->values();
        $customerTypes = ['Main Customer', 'Walking Customer'];

        $maxRows = max($zones->count(), count($filerTypes), $groups->count(), count($customerTypes), 1);
        for ($i = 0; $i < $maxRows; $i++) {
            $row = $i + 2;
            if ($zones->has($i)) {
                $reference->setCellValue('A' . $row, $zones[$i]);
            }
            if (isset($filerTypes[$i])) {
                $reference->setCellValue('B' . $row, $filerTypes[$i]);
            }
            if ($groups->has($i)) {
                $reference->setCellValue('C' . $row, $groups[$i]);
            }
            if (isset($customerTypes[$i])) {
                $reference->setCellValue('D' . $row, $customerTypes[$i]);
            }
        }

        foreach (['A', 'B', 'C', 'D'] as $col) {
            $reference->getColumnDimension($col)->setAutoSize(true);
        }

        $spreadsheet->setActiveSheetIndex(0);

        return $spreadsheet;
    }

    public function downloadTemplate(): void
    {
        $spreadsheet = $this->buildTemplateSpreadsheet();
        $writer = new Xlsx($spreadsheet);
        $writer->save('php://output');
    }

    public function importFromPath(string $path, int $userId, bool $isAdmin, array $defaultUserGroupIds): array
    {
        $spreadsheet = IOFactory::load($path);
        $sheet = $spreadsheet->getSheet(0);
        $rows = $sheet->toArray(null, true, true, false);

        if (count($rows) < 2) {
            return [
                'imported' => 0,
                'skipped' => 0,
                'errors' => ['Excel file is empty or has no data rows.'],
            ];
        }

        $headerRow = array_map(fn ($value) => trim((string) $value), $rows[0]);
        $columnIndexes = $this->resolveColumnIndexes($headerRow);

        if (!isset($columnIndexes['customer_name'])) {
            return [
                'imported' => 0,
                'skipped' => 0,
                'errors' => ['Missing required column: Customer Name'],
            ];
        }

        $imported = 0;
        $skipped = 0;
        $errors = [];
        $groupNameMap = UserGroup::query()->pluck('id', 'group_name')
            ->mapWithKeys(fn ($id, $name) => [strtolower(trim($name)) => $id]);

        for ($rowIndex = 1; $rowIndex < count($rows); $rowIndex++) {
            $excelRowNumber = $rowIndex + 1;
            $row = $rows[$rowIndex];
            $payload = $this->extractRowPayload($row, $columnIndexes);

            if ($this->isEmptyRow($payload)) {
                continue;
            }

            $payload['customer_type'] = $this->normalizeCustomerType($payload['customer_type'] ?? null);
            $payload['filer_type'] = $this->normalizeFilerType($payload['filer_type'] ?? null);
            $payload['opening_balance'] = $this->normalizeNumber($payload['opening_balance'] ?? null);

            $userGroupIds = $this->resolveUserGroupIds(
                $payload['user_groups'] ?? null,
                $isAdmin,
                $defaultUserGroupIds,
                $groupNameMap,
                $errors,
                $excelRowNumber
            );

            if ($userGroupIds === false) {
                $skipped++;
                continue;
            }

            unset($payload['user_groups']);

            $validator = Validator::make($payload, [
                'customer_name' => 'nullable',
                'customer_name_ur' => 'nullable',
                'cnic' => 'nullable',
                'filer_type' => 'nullable',
                'zone' => 'nullable',
                'contact_person' => 'nullable',
                'mobile' => 'nullable',
                'email_address' => 'nullable|email',
                'contact_person_2' => 'nullable',
                'mobile_2' => 'nullable',
                'email_address_2' => 'nullable|email',
                'opening_balance' => 'nullable|numeric',
                'address' => 'nullable',
                'address_ur' => 'nullable',
                'transport_ur' => 'nullable',
                'customer_type' => 'nullable',
            ]);

            if ($validator->fails()) {
                $skipped++;
                $errors[] = 'Row ' . $excelRowNumber . ': ' . implode(' ', $validator->errors()->all());
                continue;
            }

            if (empty($payload['customer_name']) && empty($payload['mobile'])) {
                $skipped++;
                $errors[] = 'Row ' . $excelRowNumber . ': Customer Name or Mobile is required.';
                continue;
            }

            try {
                DB::transaction(function () use ($payload, $userId, $userGroupIds) {
                    $this->createCustomer($payload, $userId, $userGroupIds);
                });
                $imported++;
            } catch (\Throwable $e) {
                $skipped++;
                $errors[] = 'Row ' . $excelRowNumber . ': ' . $e->getMessage();
            }
        }

        return compact('imported', 'skipped', 'errors');
    }

    public function createCustomer(array $data, int $userId, ?array $userGroupIds = null): Customer
    {
        $openingBalance = floatval($data['opening_balance'] ?? 0);
        $data['opening_balance'] = $openingBalance;

        $data['created_by'] = $userId;
        unset($data['customer_id']);

        if ($userGroupIds !== null) {
            $data['user_group_ids'] = $userGroupIds;
        }

        $data['status'] = $data['status'] ?? 'active';

        $customer = Customer::create($data);

        if ($openingBalance != 0.0) {
            app(PartyLedgerService::class)->postOpeningBalance('customer', $customer->id, $openingBalance, $userId);
        }

        return $customer;
    }

    protected function resolveColumnIndexes(array $headerRow): array
    {
        $indexes = [];
        $normalizedHeaders = array_map(fn ($h) => strtolower(trim($h)), $headerRow);

        foreach (self::COLUMN_MAP as $key => $label) {
            $normalizedLabel = strtolower($label);
            $position = array_search($normalizedLabel, $normalizedHeaders, true);
            if ($position !== false) {
                $indexes[$key] = $position;
            }
        }

        return $indexes;
    }

    protected function extractRowPayload(array $row, array $columnIndexes): array
    {
        $payload = [];
        foreach ($columnIndexes as $key => $index) {
            $value = $row[$index] ?? null;
            $payload[$key] = is_string($value) ? trim($value) : $value;
            if ($payload[$key] === '') {
                $payload[$key] = null;
            }
        }

        return $payload;
    }

    protected function isEmptyRow(array $payload): bool
    {
        foreach ($payload as $value) {
            if ($value !== null && $value !== '') {
                return false;
            }
        }

        return true;
    }

    protected function normalizeCustomerType(?string $value): string
    {
        $value = strtolower(trim((string) $value));
        if ($value === 'walking customer' || $value === 'walking') {
            return 'Walking Customer';
        }

        return 'Main Customer';
    }

    protected function normalizeFilerType(?string $value): string
    {
        $value = strtolower(trim((string) $value));
        if (in_array($value, ['non filer', 'non-filer', 'nonfiler'], true)) {
            return 'non filer';
        }
        if ($value === 'exempt') {
            return 'exempt';
        }

        return 'filer';
    }

    protected function normalizeNumber($value): ?float
    {
        if ($value === null || $value === '') {
            return null;
        }

        return (float) str_replace(',', '', (string) $value);
    }

    protected function resolveUserGroupIds(
        ?string $rawGroups,
        bool $isAdmin,
        array $defaultUserGroupIds,
        $groupNameMap,
        array &$errors,
        int $excelRowNumber
    ) {
        if (!$isAdmin) {
            return $defaultUserGroupIds ?: null;
        }

        if ($rawGroups === null || trim($rawGroups) === '') {
            return null;
        }

        $names = array_filter(array_map('trim', explode(',', $rawGroups)));
        $ids = [];

        foreach ($names as $name) {
            $key = strtolower($name);
            if (!$groupNameMap->has($key)) {
                $errors[] = 'Row ' . $excelRowNumber . ': Unknown user group "' . $name . '".';
                return false;
            }
            $ids[] = (int) $groupNameMap[$key];
        }

        return array_values(array_unique($ids));
    }
}
